### ISSUE TITLE
Path to image in HTML with trailing slash

### ISSUE THREAD

**Issue by cvjb** [Niflheim-uk/Doors-Smores-Docs#2]
Environment: VSCode on Linux.
Path to project: /home/user/Requierments/Maintenance_Mode/
Document type: Software Requirements Specification

Adding an image (file, not mermaid syntax) to a document in a project wiith spaces in its path will result in an icon to show a broken image reference in VSCode. It also results in a PDF and HTML export with no image. In HTML the IMG-tag has this URL: "/home/user/Requirements/Maintenance_Mode/.smoresData/14100/image.jpg**/**".
 
Note the trailing slash at the end. Removing this will fix the problem.

I would expect somehting like "/home/user/Requirements/Maintenance%20Mode/.smoresData/14100/image.jpg"

**Comment by cvjb** [comment]
Sorry wrong project :-( my fault.

BTW great tool!

**Comment by cvjb** [comment]
Sorry wrong project :-( my fault.

BTW great tool!

**Comment by Niflheim-uk** [comment]
fixed in 0.5.14
